### PR TITLE
Add PLUGIN_VERSION global variables and fix compiling on Windows

### PR DESCRIPTION
**Pull request by osprey-12**

### CODE REVIEW

**Comment by sparker256** [comment]
Thanks for the pull request and have tested on Windows and the new globals worked there. If we change the CMakeLists.txt the will break the GitHub actions so best to leave it as win.xpl and use the copy .\build\win.xpl .\FlyWithLua\win_x64\FlyWithLua.xpl command to do the same job. I see the other platforms were also missed  in the README.md so let me know how you want to proceed.

**Comment by osprey-12** [comment]
My goal is the new global variables. I made the other changes because of errors in Windows PowerShell when compiling and wasn’t aware it would break other things. I didn’t touch anything besides Windows because I was already in over my head.On Jan 29, 2023, at 3:33 PM, William Good ***@***.***> wrote:﻿
Thanks for the pull request and have tested on Windows and the new globals worked there. If we change the CMakeLists.txt the will break the GitHub actions so best to leave it as win.xpl and use the copy .\build\win.xpl .\FlyWithLua\win_x64\FlyWithLua.xpl command to do the same job. I see the other platforms were also missed  in the README.md so let me know how you want to proceed.

**Comment by sparker256** [comment]
Interesting. Before I commented here I made sure that without your changes win build changes I could build fine on Windows with out any errors. To move forward can you pull out the win build changes from the pull request and then I will accept it. If you want we can have a voice or video chat on Discord or Skype just let me know.

**Comment by osprey-12** [comment]
I reverted the Windows changes. Will that allow you to accept it (github rookie...).

**Comment by sparker256** [comment]
Yes it will thanks for your contribution.

**Pull request merged**
